ALTER TABLE "food_library_items"
ADD COLUMN "name_fr" TEXT,
ADD COLUMN "name_en" TEXT;

UPDATE "food_library_items"
SET
  "name_fr" = COALESCE("name_fr", "name"),
  "name_en" = COALESCE("name_en", "name");

UPDATE "food_library_items" AS food
SET "name_en" = translations."name_en"
FROM (
  VALUES
    ('Blanc de poulet', 'Chicken breast'),
    ('Cuisse de poulet', 'Chicken thigh'),
    ('Escalope de dinde', 'Turkey breast cutlet'),
    ('Bœuf — steak haché 5%', 'Beef — 5% ground steak'),
    ('Saumon', 'Salmon'),
    ('Thon en conserve', 'Canned tuna'),
    ('Thon frais', 'Fresh tuna'),
    ('Sardines à l''huile', 'Sardines in oil'),
    ('Sardines à l''eau', 'Sardines in water'),
    ('Maquereau', 'Mackerel'),
    ('Maquereau en conserve', 'Canned mackerel'),
    ('Crevettes', 'Shrimp'),
    ('Cabillaud', 'Cod'),
    ('Œufs entiers', 'Whole eggs'),
    ('Blancs d''œufs', 'Egg whites'),
    ('Whey protéine', 'Whey protein'),
    ('Tofu ferme', 'Firm tofu'),
    ('Tempeh', 'Tempeh'),
    ('Lentilles cuites', 'Cooked lentils'),
    ('Pois chiches cuits', 'Cooked chickpeas'),
    ('Haricots noirs cuits', 'Cooked black beans'),
    ('Edamame', 'Edamame'),
    ('Riz blanc cuit', 'Cooked white rice'),
    ('Riz complet cuit', 'Cooked brown rice'),
    ('Flocons d''avoine', 'Rolled oats'),
    ('Pâtes cuites', 'Cooked pasta'),
    ('Pâtes complètes cuites', 'Cooked whole-wheat pasta'),
    ('Pomme de terre cuite', 'Cooked potato'),
    ('Patate douce cuite', 'Cooked sweet potato'),
    ('Quinoa cuit', 'Cooked quinoa'),
    ('Boulgour cuit', 'Cooked bulgur'),
    ('Couscous cuit', 'Cooked couscous'),
    ('Pain complet', 'Whole-grain bread'),
    ('Pain blanc', 'White bread'),
    ('Tortilla blé', 'Wheat tortilla'),
    ('Huile d''olive', 'Olive oil'),
    ('Huile de coco', 'Coconut oil'),
    ('Huile de colza', 'Rapeseed oil'),
    ('Amandes', 'Almonds'),
    ('Noix', 'Walnuts'),
    ('Noix de cajou', 'Cashews'),
    ('Beurre de cacahuète', 'Peanut butter'),
    ('Avocat', 'Avocado'),
    ('Brocoli cuit', 'Cooked broccoli'),
    ('Épinards', 'Spinach'),
    ('Tomate', 'Tomato'),
    ('Concombre', 'Cucumber'),
    ('Carottes', 'Carrots'),
    ('Poivron rouge', 'Red bell pepper'),
    ('Courgette', 'Zucchini'),
    ('Haricots verts cuits', 'Cooked green beans'),
    ('Asperges', 'Asparagus'),
    ('Chou-fleur cuit', 'Cooked cauliflower'),
    ('Champignons', 'Mushrooms'),
    ('Oignon', 'Onion'),
    ('Laitue / Salade verte', 'Lettuce / green salad'),
    ('Chou kale', 'Kale'),
    ('Banane', 'Banana'),
    ('Pomme', 'Apple'),
    ('Orange', 'Orange'),
    ('Fraises', 'Strawberries'),
    ('Myrtilles', 'Blueberries'),
    ('Kiwi', 'Kiwi'),
    ('Mangue', 'Mango'),
    ('Poire', 'Pear'),
    ('Raisins', 'Grapes'),
    ('Yaourt grec (0%)', 'Greek yogurt (0%)'),
    ('Fromage blanc (0%)', 'Cottage cheese (0%)'),
    ('Lait demi-écrémé', 'Semi-skimmed milk'),
    ('Mozzarella', 'Mozzarella'),
    ('Skyr', 'Skyr')
) AS translations("name_fr", "name_en")
WHERE food."name" = translations."name_fr"
  AND (food."name_en" IS NULL OR food."name_en" = food."name");
