import type { AffiliateProduct } from '@/types'

// Produits Amazon réels — titres et images récupérés directement depuis les pages Amazon.
// Prix gérés par Amazon → afficher "Voir le prix sur Amazon" côté UI.
// Images : Amazon CDN (m.media-amazon.com), format _SL400_ (400px).
export const AFFILIATE_PRODUCTS: AffiliateProduct[] = [

  // ── SUPPLÉMENTS ─────────────────────────────────────────────────────────────

  {
    id:   'aff-s1',
    name: 'BCAA Instant Powder – Fruits Rouges 500g',
    brand: 'Bulk',
    description: '8g d\'acides aminés ramifiés par portion, saveur fruits rouges. Idéal pour la récupération et la performance musculaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dKEYQH',
    imageUrl: 'https://m.media-amazon.com/images/I/61nGXjctN8L._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['bcaa', 'acides aminés', 'récupération'],
  },
  {
    id:   'aff-s2',
    name: 'Magnésium Bisglycinate + B6 & Taurine – 180 Gélules',
    brand: 'Nutripure',
    description: 'Forme chélatée haute absorption, anti-fatigue et anti-stress. Sans effet laxatif, 100% vegan. Made in France.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/49kgRqT',
    imageUrl: 'https://m.media-amazon.com/images/I/614fLvbRYjL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['magnésium', 'stress', 'anti-fatigue'],
  },
  {
    id:   'aff-s3',
    name: 'Zinc Bisglycinate 15mg ALBION® – 90 Gélules',
    brand: 'Nutripure',
    description: 'Haute qualité ALBION®, haute biodisponibilité. Antioxydant, renfort du système immunitaire. Vegan, Made in France.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4tTejax',
    imageUrl: 'https://m.media-amazon.com/images/I/51TqGgkGRxL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['zinc', 'immunité', 'antioxydant'],
  },
  {
    id:   'aff-s4',
    name: 'L-Carnitine Carnipure 2000mg – 150 Capsules',
    brand: 'Nutripure',
    description: 'Forme pure brevetée Carnipure, idéale avant l\'entraînement. Énergie & métabolisme des graisses. Vegan, Made in France.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dx4QAT',
    imageUrl: 'https://m.media-amazon.com/images/I/51ljbCkHuKL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['WEIGHT_LOSS', 'ENDURANCE'],
    tags: ['carnitine', 'brûle-graisses', 'énergie'],
  },
  {
    id:   'aff-s5',
    name: 'Oméga 3 Epax 2400mg – EPA 1260mg & DHA 900mg',
    brand: 'Nutripure',
    description: 'Huile de poisson sauvage, TotOx <7 (pureté maximale). Bénéfices cerveau, vision & cœur. Inodore, 90 capsules.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4wSCzfJ',
    imageUrl: 'https://m.media-amazon.com/images/I/616PBUeRuxL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['omega3', 'EPA', 'DHA', 'cerveau'],
  },
  {
    id:   'aff-s6',
    name: 'Multivitamines & Minéraux – 21 Nutriments – 60 Gélules',
    brand: 'Nutripure',
    description: 'Vitamines A, B, C, D & E + Zinc & Magnésium. Immunité, énergie et antioxydant pour sportifs actifs. Made in France.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dJnPqK',
    imageUrl: 'https://m.media-amazon.com/images/I/51j7Haa-dOL._SL400_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['vitamines', 'minéraux', 'immunité'],
  },

  // ── ÉQUIPEMENT ───────────────────────────────────────────────────────────────

  {
    id:   'aff-e1',
    name: 'Sangles de Levage Big Grip 21,5" – Nylon & Caoutchouc',
    brand: 'Harbinger',
    description: 'Sangles de levage avec caoutchouc intégré pour un grip supérieur. Idéales pour soulevé de terre et rowing lourd.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/43xBxbs',
    imageUrl: 'https://m.media-amazon.com/images/I/81uEJoNx2pL._SL400_.jpg',
    commissionRateMin: 4, commissionRateMax: 7,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['sangles', 'powerlifting', 'grip', 'harbinger'],
  },
  {
    id:   'aff-e2',
    name: 'Sangles de Levage Femme – Coton Rembourré Rose 21"',
    brand: 'Harbinger',
    description: 'Sangles haltérophilie spécial femme, coton doux et rembourré. Maintien du poignet optimal pour des charges maximales.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4tUdvlJ',
    imageUrl: 'https://m.media-amazon.com/images/I/81wxh-XIjAL._SL400_.jpg',
    commissionRateMin: 4, commissionRateMax: 7,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['sangles', 'femme', 'musculation', 'harbinger'],
  },
  {
    id:   'aff-e3',
    name: 'Pistolet de Massage Musculaire Percussif',
    brand: 'Amazon',
    description: 'Pistolet de massage pour récupération musculaire. Réduit les courbatures et les tensions après l\'entraînement.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/431JFkm',
    imageUrl: 'https://m.media-amazon.com/images/I/71fqzNCpHUL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['massage', 'récupération', 'percussif'],
  },
  {
    id:   'aff-e4',
    name: 'Masseur Cervical & Dos Shiatsu – 16 Nœuds & Chaleur',
    brand: 'Boriwat',
    description: 'Massage shiatsu 16 nœuds, 2 zones de chaleur (38–59°C), grand format 38cm. Nuque, épaules, lombaires, jambes.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4e7Aipq',
    imageUrl: 'https://m.media-amazon.com/images/I/81gi67LrLWL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['massage', 'cervical', 'shiatsu', 'chaleur'],
  },
  {
    id:   'aff-e5',
    name: 'Bandes Élastiques Musculation – 5 Niveaux de Résistance',
    brand: 'Fokky',
    description: '5 niveaux de résistance, poignées et ancre de porte incluses. Idéales pour yoga, pilates, fitness et CrossFit.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4v520sG',
    imageUrl: 'https://m.media-amazon.com/images/I/71lz3Nq7-OL._SL400_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['FLEXIBILITY', 'GENERAL_FITNESS', 'WEIGHT_LOSS'],
    tags: ['élastiques', 'résistance', 'fitness', 'crossfit'],
  },

  // ── VÊTEMENTS ────────────────────────────────────────────────────────────────

  {
    id:   'aff-c1',
    name: 'Gants Open Training – Crossfit & Musculation',
    brand: 'Bear Grip',
    description: 'Gants open finger pour CrossFit, musculation, calisthenics et haltérophilie. Confort et grip optimaux.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/3RwOMXg',
    imageUrl: 'https://m.media-amazon.com/images/I/717-slOBEjL._SL400_.jpg',
    commissionRateMin: 7, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['gants', 'crossfit', 'grip', 'musculation'],
  },

  // ── LIVRES ───────────────────────────────────────────────────────────────────

  {
    id:   'aff-b1',
    name: 'Encyclopédie Musculation – Oscar Morán',
    brand: 'Éditions',
    description: 'La référence incontournable de la musculation. Exercices illustrés en détail pour tous les groupes musculaires.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/3PZKqaJ',
    imageUrl: 'https://m.media-amazon.com/images/I/71gazUwsoKL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['encyclopédie', 'musculation', 'anatomie', 'technique'],
  },
  {
    id:   'aff-b2',
    name: 'CrossFit pour Tous – Guide Ultime',
    brand: 'Amazon',
    description: 'Devenir fort, sec et endurant grâce au CrossFit. Le guide complet pour débutants et intermédiaires.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4uEfCeI',
    imageUrl: 'https://m.media-amazon.com/images/I/61mCg+5X9dL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['crossfit', 'guide', 'entraînement', 'force'],
  },
  {
    id:   'aff-b3',
    name: 'Carnet d\'Entraînement Musculation',
    brand: 'FIT&FRENCHY',
    description: 'Suivez vos progrès, fixez-vous des objectifs réalistes et célébrez vos résultats. Carnet de suivi complet.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/3PnmjTe',
    imageUrl: 'https://m.media-amazon.com/images/I/51v9zZKpc0L._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS', 'MUSCLE_GAIN'],
    tags: ['carnet', 'suivi', 'objectifs', 'progrès'],
  },
  {
    id:   'aff-b4',
    name: 'Musculation – Les 5 Piliers (Bible 5-en-1)',
    brand: 'DigitalBook Factory',
    description: 'Nutrition, entraînement, performance, préparation et récupération : tout ce qu\'il faut pour progresser efficacement.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4dO6A7C',
    imageUrl: 'https://m.media-amazon.com/images/I/61kR7Wm2S5L._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['musculation', 'nutrition', 'guide', 'bible'],
  },
  {
    id:   'aff-b5',
    name: '99 Façons de Ne Jamais Devenir une Vieille Râleuse',
    brand: 'Amazon',
    description: 'Le guide drôle pour les femmes qui gardent leur humour et leur caractère. Un cadeau original et plein d\'esprit.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4dyr2L2',
    imageUrl: 'https://m.media-amazon.com/images/I/715pk23sYaL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['humour', 'cadeau', 'femme', 'lifestyle'],
  },
  {
    id:   'aff-b6',
    name: 'Les 100 Recettes du Sportif – Nouchka Simic',
    brand: 'Marabout',
    description: 'Performance, prise de masse, perte de poids : 100 recettes adaptées à vos objectifs sportifs. Nutrition optimisée.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4v6FnEg',
    imageUrl: 'https://m.media-amazon.com/images/I/71yFEZxfseL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['WEIGHT_LOSS', 'MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['recettes', 'sport', 'nutrition', 'alimentation'],
  },
  {
    id:   'aff-b7',
    name: '111 Recettes 0 Point – Perte de Poids sans Stress',
    brand: 'Amazon',
    description: '111 recettes zéro point saines et savoureuses pour perdre du poids facilement. Plan de repas sur 30 jours inclus.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4fP27Ee',
    imageUrl: 'https://m.media-amazon.com/images/I/71lePf2W3WL._SL400_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['WEIGHT_LOSS'],
    tags: ['recettes', 'perte de poids', 'zéro point', 'cuisine'],
  },
  {
    id:   'aff-b8',
    name: 'Maigrir avec l\'Air Fryer en 60 Jours',
    brand: 'Amazon',
    description: 'Plats rapides et équilibrés pour perdre du poids et rester motivé. Programme complet sur 60 jours.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4e6oDaw',
    imageUrl: 'https://m.media-amazon.com/images/I/7194s9Cjo5L._SL400_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['WEIGHT_LOSS'],
    tags: ['air fryer', 'minceur', 'recettes', 'cuisine'],
  },
  {
    id:   'aff-b9',
    name: 'Menus Protéinés pour Rééquilibrage Alimentaire',
    brand: 'Amazon',
    description: '20 menus complets riches en protéines pour maigrir sans frustration. Rééquilibrage alimentaire durable.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4utUXtD',
    imageUrl: 'https://m.media-amazon.com/images/I/61XJC4Z8vHL._SL400_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['WEIGHT_LOSS', 'MUSCLE_GAIN'],
    tags: ['protéines', 'menus', 'rééquilibrage', 'minceur'],
  },
  {
    id:   'aff-b10',
    name: 'Perte de Gras – Maîtriser votre Composition Corporelle',
    brand: 'Amazon',
    description: 'Maîtrisez la perte de gras mieux que 99,9% de la population et atteignez votre corps de rêve. Guide complet.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/3Q4atgT',
    imageUrl: 'https://m.media-amazon.com/images/I/61l2mLTGU4L._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['WEIGHT_LOSS'],
    tags: ['perte de gras', 'composition corporelle', 'guide'],
  },

  // ── SUPPLÉMENTS (nouveaux) ───────────────────────────────────────────────────

  {
    id:   'aff-s7',
    name: 'Nutripure Pack Les Incontournables – Magnésium + Oméga 3 + Multivitamines',
    brand: 'Nutripure',
    description: 'Pack 3-en-1 : Magnésium Bisglycinate, Oméga 3 & Multivitamines. Les essentiels santé & bien-être pour 1 mois complet. Made in France.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4nRDaKl',
    imageUrl: 'https://m.media-amazon.com/images/I/41wltlAGyeL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['magnésium', 'oméga3', 'vitamines', 'pack'],
  },
  {
    id:   'aff-s8',
    name: 'Bulk Pure Whey Protéine en Poudre Vanille – 1 kg',
    brand: 'Bulk',
    description: '23g protéines par portion, 5g BCAA, faible en sucre. Favorise la croissance et la récupération musculaires, mélange facile.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3Q03d5I',
    imageUrl: 'https://m.media-amazon.com/images/I/61O9tALJqBL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'protéine', 'vanille', 'récupération'],
  },
  {
    id:   'aff-s9',
    name: 'Nutripure Whey Isolate Native – 94% Protéines – 2 kg',
    brand: 'Nutripure',
    description: '94% protéines, 25% BCAA, 52% EAA. Saveur neutre, 2kg. Idéale pour le développement musculaire. Vegan-friendly, Made in France.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/49niZy4',
    imageUrl: 'https://m.media-amazon.com/images/I/71oLeRsnKvL._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['whey isolate', 'protéine', 'BCAA', 'EAA'],
  },
  {
    id:   'aff-s10',
    name: 'Nutripure Pure Gainer Prise de Masse Sèche – 1,2 kg',
    brand: 'Nutripure',
    description: 'Whey Native, Collagène & Farine d\'Avoine. 28g protéines, 35g glucides. Sans gluten & OGM. Made in France.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3PMl7ZE',
    imageUrl: 'https://m.media-amazon.com/images/I/51mkGp4TtWL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['gainer', 'prise de masse', 'collagène', 'avoine'],
  },
  {
    id:   'aff-s11',
    name: 'Nutrimuscle Whey Isolate Native – Lait Français – 1 kg',
    brand: 'Nutrimuscle',
    description: 'Jusqu\'à 85% de protéines par dose. Isolat de whey native issu de lait français. 1kg nature pour une prise de masse musculaire propre.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3Ru2vOB',
    imageUrl: 'https://www.nutrimuscle.com/cdn/shop/files/IWES050010E3-WHEY-EASYSHAKE-500G-C-1500ML-V1.png?v=1755589318&width=416',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['whey isolate', 'protéine', 'lait français', 'pureté'],
  },
  {
    id:   'aff-s12',
    name: 'Nutrimuscle Créatine Monohydrate Creapure – 120 Gélules',
    brand: 'Nutrimuscle',
    description: 'Créatine 100% pure Creapure®. Prise de masse musculaire & force. Complément idéal à la Whey Protéine.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4tZq0wr',
    imageUrl: 'https://m.media-amazon.com/images/I/61wpOczMp5L._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['créatine', 'Creapure', 'force', 'masse'],
  },
  {
    id:   'aff-s13',
    name: 'Nutrimuscle Musclemasse Hard Gainer Chocolat – 1,8 kg',
    brand: 'Nutrimuscle',
    description: 'Whey protéine, Maltodextrine et Dextrose pour prise de masse intense. 1,8kg saveur chocolat.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4fOWlm2',
    imageUrl: 'https://m.media-amazon.com/images/I/61U0ETuB7oL._SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['gainer', 'prise de masse', 'chocolat', 'maltodextrine'],
  },
  {
    id:   'aff-s14',
    name: 'MyProtein Weight Gainer Protéine Whey',
    brand: 'MyProtein',
    description: 'Weight Gainer riche en protéines whey et glucides pour favoriser une prise de masse rapide et efficace.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3PDAtzF',
    imageUrl: 'https://m.media-amazon.com/images/I/61u5nUUM2WL._SL400_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['gainer', 'whey', 'myprotein', 'masse'],
  },
  {
    id:   'aff-s15',
    name: 'Myprotein Impact Whey Protein – 1 kg',
    brand: 'MyProtein',
    description: 'Whey protéine classique Myprotein. 1kg, disponible en plusieurs saveurs. Idéale pour la récupération et le développement musculaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4u4bfZj',
    imageUrl: 'https://m.media-amazon.com/images/I/51TAQnfNZKL._SL400_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'protéine', 'myprotein', 'récupération'],
  },
  {
    id:   'aff-s16',
    name: 'Créatine Monohydrate Micronisée en Poudre – 250 g',
    brand: 'Bulk',
    description: 'Créatine micronisée pure, non aromatisée, 250g. Complément alimentaire de référence pour la masse et la force musculaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4fGMlv8',
    imageUrl: 'https://m.media-amazon.com/images/I/71t8DCFhtuL._SL400_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['créatine', 'monohydrate', 'poudre', 'force'],
  },

  // ── ÉQUIPEMENT (nouveaux) ────────────────────────────────────────────────────

  {
    id:   'aff-e6',
    name: 'PICSIL Ceinture Lombaire Lockpro Néoprène – Powerlifting',
    brand: 'PICSIL',
    description: 'Ceinture lombaire néoprène pour Powerlifting, Cross Training et Functional. Double fermeture réglable pour un maintien optimal.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4dz6VfL',
    imageUrl: 'https://m.media-amazon.com/images/I/61BgdQeLM7L._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['ceinture', 'lombaire', 'powerlifting', 'néoprène'],
  },
  {
    id:   'aff-e7',
    name: 'Eric Flag Ceinture Lestée Musculation – Jusqu\'à 300 kg',
    brand: 'Eric Flag',
    description: 'Ceinture de lest avec chaîne ou corde pour Street Workout et Calisthenics. Adaptée à toutes morphologies. Charge max 300 kg.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4uEahUI',
    imageUrl: 'https://m.media-amazon.com/images/I/71CS864c8DL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['ceinture lestée', 'calisthenics', 'dips', 'lest'],
  },
  {
    id:   'aff-e8',
    name: 'PICSIL Ceinture Powerlifting Cuir Synthétique – Réglable',
    brand: 'PICSIL',
    description: 'Ceinture Powerlifting en cuir synthétique avec velcro. Support lombaire pour Squat, Développé Couché et Deadlift.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4wWA24k',
    imageUrl: 'https://m.media-amazon.com/images/I/81VJnFxvabL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture', 'powerlifting', 'cuir', 'squat'],
  },
  {
    id:   'aff-e9',
    name: 'Eric Flag Ceinture Lestée Pro – Street Workout & Calisthenics',
    brand: 'Eric Flag',
    description: 'Ceinture de lest professionnelle pour musculation, Street Workout et Calisthenics. Chaîne ou corde, adaptée à toutes morphologies.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4wMmqs5',
    imageUrl: 'https://m.media-amazon.com/images/I/71Ei-Cg0qhL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['ceinture lestée', 'calisthenics', 'street workout', 'pro'],
  },
  {
    id:   'aff-e10',
    name: 'Fitgriff® Ceinture Lestée avec Chaîne + 2 Mousquetons',
    brand: 'Fitgriff',
    description: 'Ceinture de musculation lestée avec chaîne et 2 mousquetons inclus. Pour Haltérophilie, Bodybuilding, Dips, CrossFit et Gym.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4wRbMQN',
    imageUrl: 'https://m.media-amazon.com/images/I/812kCHGv5gL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['ceinture lestée', 'chaîne', 'dips', 'crossfit'],
  },
  {
    id:   'aff-e11',
    name: 'Warrior Gear Ceinture Levier 13 mm – Powerlifting & Squat',
    brand: 'Warrior Gear',
    description: 'Ceinture à levier 13mm pour Powerlifting, musculation et fitness. Idéale pour le Squat et le Soulevé de terre.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4dvNMv8',
    imageUrl: 'https://m.media-amazon.com/images/I/71zPAfcreHL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture', 'levier', 'powerlifting', 'squat'],
  },
  {
    id:   'aff-e12',
    name: 'AQF Ceinture Levier 4" × 13 mm – Powerlifting & Deadlift',
    brand: 'AQF',
    description: 'Ceinture avec levier boucle, 4" large × 13mm. Pour Powerlifting, Fitness, Gym et Deadlifts.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4vwnxLl',
    imageUrl: 'https://m.media-amazon.com/images/I/71Nq+lXQOXL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture', 'levier', 'powerlifting', 'deadlift'],
  },
  {
    id:   'aff-e13',
    name: 'Machine de Torsion Abdominale Réglable – Plateau Silencieux',
    brand: 'Gresonic',
    description: 'Plateau de torsion abdominale silencieux pour la maison. Affichage numérique pour suivre le temps. Idéal pour la taille et les obliques.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4nO5rBA',
    imageUrl: 'https://m.media-amazon.com/images/I/616AyR+ZQUL._SL400_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['WEIGHT_LOSS', 'GENERAL_FITNESS'],
    tags: ['abdominaux', 'torsion', 'taille', 'maison'],
  },
  {
    id:   'aff-e14',
    name: 'Myprotein Shaker Pro 600 ml Limited Edition – Noir',
    brand: 'MyProtein',
    description: 'Shaker Limited Edition Noir pour la préparation de tes shakes protéinés. Étanche, facile à nettoyer.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4e6fSND',
    imageUrl: 'https://m.media-amazon.com/images/I/51asQEiKp0L._SL400_.jpg',
    commissionRateMin: 4, commissionRateMax: 7,
    fitnessGoals: ['GENERAL_FITNESS', 'MUSCLE_GAIN'],
    tags: ['shaker', 'bouteille', 'myprotein', 'accessoire'],
  },

  // ── BIOTECHUSA ───────────────────────────────────────────────────────────────

  {
    id:   'aff-bt1',
    name: 'BioTechUSA Iso Whey Zero Grass-Fed – Chocolat',
    brand: 'BioTechUSA',
    description: 'Whey Isolat premium Grass-Fed, sans enzymes, sans gluten. Haute teneur en protéines, zéro sucre ajouté. Idéal pour la prise de masse musculaire sèche.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3RyOL57',
    imageUrl: 'https://m.media-amazon.com/images/I/71IQMxKpfyL._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['whey isolat', 'grass-fed', 'chocolat', 'sans gluten'],
  },
  {
    id:   'aff-bt2',
    name: 'BioTechUSA Iso Whey Zero Black – 90% Protéines – Créatine & Zinc',
    brand: 'BioTechUSA',
    description: '90% protéines de qualité, enrichi en créatine, zinc et vitamine B3. 1816g saveur vanille. Sans sucre, sans lactose, sans gluten.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dNq8ZJ',
    imageUrl: 'https://m.media-amazon.com/images/I/71aK8x1L9XL._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['whey isolat', 'créatine', 'zinc', 'vanille'],
  },
  {
    id:   'aff-bt3',
    name: 'BioTechUSA Clear Collagen Pro – Collagène Hydrolysé & Acide Hyaluronique',
    brand: 'BioTechUSA',
    description: 'Boisson rafraîchissante au collagène hydrolysé et acide hyaluronique. Soutient les articulations, la peau et la mobilité.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4wT9Pn1',
    imageUrl: 'https://m.media-amazon.com/images/I/71-VQ5d1qPL._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['collagène', 'acide hyaluronique', 'articulations', 'récupération'],
  },
  {
    id:   'aff-bt4',
    name: 'BioTechUSA 100% Créatine Monohydrate – Qualité Pharmaceutique – Micronisée',
    brand: 'BioTechUSA',
    description: 'Créatine monohydrate de qualité pharmaceutique, micronisée pour une absorption maximale. Améliore la force, la puissance et la prise de masse.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4a8LwYn',
    imageUrl: 'https://m.media-amazon.com/images/I/617fZIdA1RL._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['créatine', 'monohydrate', 'force', 'puissance'],
  },
  {
    id:   'aff-bt5',
    name: 'BioTechUSA Hyper Mass – Gainer Glucides & Protéines – Chocolat',
    brand: 'BioTechUSA',
    description: 'Gainer haute énergie avec mélange de glucides complexes et protéines. Formule optimisée pour une prise de masse musculaire rapide. Saveur chocolat.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4wVQ520',
    imageUrl: 'https://m.media-amazon.com/images/I/61IQXPPktWL._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['gainer', 'prise de masse', 'glucides', 'chocolat'],
  },
  {
    id:   'aff-bt6',
    name: 'BioTechUSA EAA Capsules – 3200mg – 9 Acides Aminés Essentiels',
    brand: 'BioTechUSA',
    description: '3200mg des 9 acides aminés essentiels par portion en gélules. Ratio OMS recommandé. Vegan, sans sucre, sans gluten. Récupération et maintien musculaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4wT9TDh',
    imageUrl: 'https://m.media-amazon.com/images/I/61UgJJLxbjL._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['EAA', 'acides aminés', 'récupération', 'gélules'],
  },
  {
    id:   'aff-bt7',
    name: 'BioTechUSA EAA Zero – 7160mg EAA/Portion – Vegan – Sans Sucre',
    brand: 'BioTechUSA',
    description: '7160mg d\'acides aminés essentiels par portion en poudre. Ratio OMS, vegan, sans sucre, sans gluten. Idéal pendant et après l\'entraînement.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3Pseb3R',
    imageUrl: 'https://m.media-amazon.com/images/I/81VV6nF-g8L._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['EAA', 'acides aminés', 'vegan', 'sans sucre'],
  },
  {
    id:   'aff-bt8',
    name: 'BioTechUSA BCAA + Glutamine Zero – 40 Portions – Vegan',
    brand: 'BioTechUSA',
    description: 'Mélange BCAA et L-Glutamine en poudre. 40 portions, vegan, sans sucre, sans gluten. Soutient la récupération musculaire et réduit la fatigue.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dQRWfS',
    imageUrl: 'https://m.media-amazon.com/images/I/61yfd3Pj45L._AC_SL400_.jpg',
    commissionRateMin: 10, commissionRateMax: 15,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['BCAA', 'glutamine', 'récupération', 'vegan'],
  },
]

/** Returns all affiliate products belonging to the given category string. */
export function getProductsByCategory(category: string) {
  return AFFILIATE_PRODUCTS.filter((p) => p.category === category)
}

/** Returns all affiliate products whose fitnessGoals array includes the given goal string. */
export function getProductsByGoal(goal: string) {
  return AFFILIATE_PRODUCTS.filter((p) => p.fitnessGoals.includes(goal as never))
}
