import type { AffiliateProduct } from '@/types'

export const CANADA_AFFILIATE_PRODUCTS: AffiliateProduct[] = [

  // --- SUPPLEMENTS ----------------------------------------------------------

  {
    id: 'ca-s1',
    name: 'Canadian Protein Vegan Blend – Vanille 1 kg',
    brand: 'Canadian Protein',
    description: 'Mélange protéiné 100 % végétal (pois, riz brun, chanvre) saveur vanille. 22 g de protéines par portion.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vDrQVd',
    imageUrl: 'https://m.media-amazon.com/images/I/61wYYNiBI7L._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['vegan', 'protéine végétale', 'vanille', 'canada'],
  },
  {
    id: 'ca-s2',
    name: 'Canadian Protein Whey Concentrate – Vanille 1 kg',
    brand: 'Canadian Protein',
    description: 'Whey concentrée 24 g de protéines par portion. Faible en glucides, riche en BCAA. Saveur vanille.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dR5KXX',
    imageUrl: 'https://m.media-amazon.com/images/I/61k2IwTW9jL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'concentré', 'vanille', 'canada'],
  },
  {
    id: 'ca-s3',
    name: 'Canadian Protein Whey Concentrate – Chocolat 1 kg',
    brand: 'Canadian Protein',
    description: 'Whey concentrée 24 g de protéines par portion. Faible en glucides, riche en BCAA. Saveur chocolat.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4va0FRi',
    imageUrl: 'https://m.media-amazon.com/images/I/61ib-2HbiqL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'concentré', 'chocolat', 'canada'],
  },
  {
    id: 'ca-s4',
    name: 'Canadian Protein Whey Isolate – Nature 1 kg',
    brand: 'Canadian Protein',
    description: 'Isolat de whey 27 g de protéines, 0 g de sucre. Idéal pour la sèche et les régimes keto.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4agpymk',
    imageUrl: 'https://m.media-amazon.com/images/I/61WJzHSsKqL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['whey isolate', 'nature', 'keto', 'canada'],
  },
  {
    id: 'ca-s5',
    name: 'Canadian Protein Whey Isolate – Vanille 2 kg',
    brand: 'Canadian Protein',
    description: 'Grand format 2 kg – Isolat de whey 27 g de protéines, faible en glucides. Saveur vanille.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dJhfQU',
    imageUrl: 'https://m.media-amazon.com/images/I/61hbzeMg8SL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['whey isolate', 'vanille', '2 kg', 'canada'],
  },
  {
    id: 'ca-s6',
    name: 'Canadian Protein Créatine Monohydrate – 454 g',
    brand: 'Canadian Protein',
    description: 'Créatine monohydrate pure. Améliore la force, la puissance et la performance musculaire. Keto friendly.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dRiX2H',
    imageUrl: 'https://m.media-amazon.com/images/I/41DEEgNlsUL._AC_SL1000_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['créatine', 'monohydrate', 'force', 'canada'],
  },
  {
    id: 'ca-s7',
    name: 'Canadian Protein Caséine Micellaire – Chocolat 1 kg',
    brand: 'Canadian Protein',
    description: 'Caséine micellaire à digestion lente, 25.5 g de protéines. Nourrit les muscles pendant le sommeil.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3Pu1CFe',
    imageUrl: 'https://m.media-amazon.com/images/I/61i8y6HQinL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['caséine', 'nuit', 'chocolat', 'canada'],
  },
  {
    id: 'ca-s8',
    name: 'Canadian Protein L-Arginine – 454 g',
    brand: 'Canadian Protein',
    description: 'L-Arginine pour booster le monoxyde d\'azote, la vascularité, l\'énergie et la performance cardiaque.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vmCory',
    imageUrl: 'https://m.media-amazon.com/images/I/618q0Xu4YDL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['L-arginine', 'pump', 'vascularité', 'canada'],
  },
  {
    id: 'ca-s9',
    name: 'Canadian Protein Acetyl L-Carnitine – 454 g',
    brand: 'Canadian Protein',
    description: 'Acetyl L-Carnitine pour améliorer le métabolisme, la concentration et réduire la fatigue musculaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vdcFBB',
    imageUrl: 'https://m.media-amazon.com/images/I/61AwyV-3PGL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['WEIGHT_LOSS', 'ENDURANCE'],
    tags: ['carnitine', 'métabolisme', 'énergie', 'canada'],
  },
  {
    id: 'ca-s10',
    name: 'Canadian Protein L-Leucine – 454 g',
    brand: 'Canadian Protein',
    description: 'L-Leucine essentielle pour la synthèse protéique, la prise de masse et la gestion du poids.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4fPZTVh',
    imageUrl: 'https://m.media-amazon.com/images/I/61aqTnRjr+L._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['leucine', 'acides aminés', 'synthèse protéique', 'canada'],
  },
  {
    id: 'ca-s11',
    name: 'Canadian Protein Taurine – 454 g',
    brand: 'Canadian Protein',
    description: 'Taurine pure pour la santé cardiovasculaire, l\'endurance et le support du système nerveux.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4fc3vkc',
    imageUrl: 'https://m.media-amazon.com/images/I/61OvPF1VfUL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['taurine', 'cardio', 'endurance', 'canada'],
  },
  {
    id: 'ca-s12',
    name: 'ALLMAX AllWhey Classic – Chocolat 5 lbs',
    brand: 'ALLMAX',
    description: 'Whey classique ALLMAX, 30 g de protéines par scoop. Sans gluten, faible en sucre. Saveur chocolat.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dRBPi5',
    imageUrl: 'https://m.media-amazon.com/images/I/61BywNWInvL._AC_SL1000_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'allmax', 'chocolat', 'canada'],
  },
  {
    id: 'ca-s13',
    name: 'ALLMAX HEXAPRO – Chocolat 5 lb',
    brand: 'ALLMAX',
    description: 'Protéine multi-sources à libération étalée sur 8h. 25 g de protéines, 0 sucre, 52 portions.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4flMHYd',
    imageUrl: 'https://m.media-amazon.com/images/I/619k530RFqL._AC_SL1000_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['hexapro', 'multi-sources', 'libération lente', 'canada'],
  },
  {
    id: 'ca-s14',
    name: 'ALLMAX ISONATURAL Whey Isolate – Chocolat 5 lb',
    brand: 'ALLMAX',
    description: 'Isolat de whey 27 g de protéines, 0 g de matières grasses et sucre. 99 % sans lactose.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4va0K7y',
    imageUrl: 'https://m.media-amazon.com/images/I/61ZeoSBsR0L._AC_SL1000_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['isolate', 'sans lactose', 'chocolat', 'canada'],
  },
  {
    id: 'ca-s15',
    name: 'ALLMAX Allmass Gainer – Vanille 5 lbs',
    brand: 'ALLMAX',
    description: 'Mass gainer avancé 2000 calories par portion. Formule haute énergie pour prise de masse rapide.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vDrXQD',
    imageUrl: 'https://m.media-amazon.com/images/I/619s-JQ4PlL._AC_SL1000_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['gainer', 'masse', '2000 calories', 'canada'],
  },
  {
    id: 'ca-s16',
    name: 'ALLMAX QUICKMASS – Vanille 3.5 lb',
    brand: 'ALLMAX',
    description: 'Gainer de prise de masse rapide. Calories denses et glucides complexes pour progresser vite.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vdcNRB',
    imageUrl: 'https://m.media-amazon.com/images/I/71C+tedaNCL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['quickmass', 'gainer', 'prise de masse', 'canada'],
  },
  {
    id: 'ca-s17',
    name: 'ALLMAX AllWhey Classic – Cookies & Cream 5 lbs',
    brand: 'ALLMAX',
    description: 'Whey classique ALLMAX 30 g de protéines, sans gluten. Saveur cookies & cream gourmande.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vgVBuD',
    imageUrl: 'https://m.media-amazon.com/images/I/61po90ctvDL._AC_SL1000_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'cookies', 'allmax', 'canada'],
  },
  {
    id: 'ca-s18',
    name: 'ON Gold Standard Whey – Vanille 2.27 kg',
    brand: 'Optimum Nutrition',
    description: 'La référence mondiale : Gold Standard 100 % Whey, 24 g de protéines. Saveur vanilla ice cream.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3Qb5zyH',
    imageUrl: 'https://m.media-amazon.com/images/I/71wbpFaSx3L._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['gold standard', 'whey', 'vanille', 'canada'],
  },
  {
    id: 'ca-s19',
    name: 'ON Gold Standard Whey – Chocolat 2.27 kg',
    brand: 'Optimum Nutrition',
    description: 'Gold Standard 100 % Whey, 24 g de protéines. Saveur extreme milk chocolate, 70 portions.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4wVTxK2',
    imageUrl: 'https://m.media-amazon.com/images/I/711Lq+gNUtL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['gold standard', 'whey', 'chocolat', 'canada'],
  },
  {
    id: 'ca-s20',
    name: 'ON Gold Standard Whey – Vanille Française 2.27 kg',
    brand: 'Optimum Nutrition',
    description: 'Gold Standard 100 % Whey, 24 g de protéines. Saveur french vanilla douce et crémeuse.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4uoy8qJ',
    imageUrl: 'https://m.media-amazon.com/images/I/81OLXaXHF6L._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['gold standard', 'french vanilla', 'ON', 'canada'],
  },
  {
    id: 'ca-s21',
    name: 'ON Gold Standard Whey – French Vanilla Creme 2.27 kg',
    brand: 'Optimum Nutrition',
    description: 'Gold Standard 100 % Whey, 24 g de protéines. Saveur french vanilla creme, format medium.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4uYwFbL',
    imageUrl: 'https://m.media-amazon.com/images/I/71i5BUUrK8L._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['gold standard', 'vanilla creme', 'ON', 'canada'],
  },
  {
    id: 'ca-s22',
    name: 'ON Pro Gainer Double Chocolat 10.19 lbs',
    brand: 'Optimum Nutrition',
    description: 'Mass gainer premium 650 calories, 60 g de protéines et 82 g de glucides. Idéal pour la prise de masse.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/43CiY5X',
    imageUrl: 'https://m.media-amazon.com/images/I/71cLMd7kpoL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['pro gainer', 'masse', 'double chocolat', 'canada'],
  },
  {
    id: 'ca-s23',
    name: 'ON Pro Complex – Rocky Road 4.6 lbs',
    brand: 'Optimum Nutrition',
    description: 'Protéine multi-sources premium. Mélange de whey isolate, hydrolysé et concentré. Saveur rocky road.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vgVHCv',
    imageUrl: 'https://m.media-amazon.com/images/I/61kf2YGzeuL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['pro complex', 'multi-sources', 'rocky road', 'canada'],
  },
  {
    id: 'ca-s24',
    name: 'Muscletech Nitro-Tech Whey – Vanilla Cream 5 lb',
    brand: 'MuscleTech',
    description: 'Formule ultra-avancée 30 g de whey isolate + peptides, 3 g de créatine et 6.8 g de BCAA.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4uoyb5T',
    imageUrl: 'https://m.media-amazon.com/images/I/81BKInFGbBL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['nitro-tech', 'muscletech', 'isolate', 'canada'],
  },
  {
    id: 'ca-b4',
    name: 'Canadian Protein Vegan Blend – Chocolat 1 kg',
    brand: 'Canadian Protein',
    description: 'Protéine végétale 22 g (riz brun, chanvre, pois isolate) saveur chocolat. Post-workout plant-based.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/43DyEG8',
    imageUrl: 'https://m.media-amazon.com/images/I/71UwU7xYamL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['vegan', 'protéine végétale', 'chocolat', 'canada'],
  },
  {
    id: 'ca-b5',
    name: 'Sports Research Oméga-3 Triple Force – 90 capsules',
    brand: 'Sports Research',
    description: 'Oméga-3 ultra-concentré issu de pollock sauvage d\'Alaska. EPA + DHA pour le cœur, le cerveau et le système immunitaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4wXXSfL',
    imageUrl: 'https://m.media-amazon.com/images/I/61uoTNIauxL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['oméga-3', 'EPA', 'DHA', 'canada'],
  },
  {
    id: 'ca-b7',
    name: 'MAV Nutrition Oméga-3 Triple Force – 120 capsules',
    brand: 'MAV Nutrition',
    description: '3600 mg d\'huile de poisson, 2100 mg d\'oméga-3 (1300 mg EPA + 860 mg DHA). Sans renvoi.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4ecTKBh',
    imageUrl: 'https://m.media-amazon.com/images/I/71ISfOqWzDL._AC_SL1500_.jpg',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['oméga-3', 'poisson', 'capsules', 'canada'],
  },

  // --- EQUIPMENT ------------------------------------------------------------

  {
    id: 'ca-s25',
    name: 'RDX Ceinture de Musculation – Auto-Lock',
    brand: 'RDX',
    description: 'Ceinture de levage 4" avec boucle auto-lock. Soutien lombaire réglable pour deadlift, squat et WOD.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3PJlbcF',
    imageUrl: 'https://m.media-amazon.com/images/I/917lEodv3uL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture', 'lombaire', 'auto-lock', 'canada'],
  },
  {
    id: 'ca-e1',
    name: 'PICSIL Ceinture Lombaire Néoprène – Compétition',
    brand: 'PICSIL',
    description: 'Ceinture lombaire officielle de compétition en néoprène. Boucle polyvalente pour powerlifting et cross training.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3PRFPHp',
    imageUrl: 'https://m.media-amazon.com/images/I/61XBcCQ4ZXL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture', 'néoprène', 'compétition', 'canada'],
  },
  {
    id: 'ca-e2',
    name: 'Gymreapers Ceinture Haltérophilie – Cuir',
    brand: 'Gymreapers',
    description: 'Ceinture en cuir véritable avec boucle ajustable. Soutien du bas du dos pour squat et deadlift.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/49qMsHA',
    imageUrl: 'https://m.media-amazon.com/images/I/61q1ypxJnoL._AC_SL1024_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture', 'cuir', 'haltérophilie', 'canada'],
  },
  {
    id: 'ca-e3',
    name: 'Gymreapers GripLink Sangles de Levage – D-Ring',
    brand: 'Gymreapers',
    description: 'Sangles de levage robustes avec bague D et billes anti-glisse en silicone. Pour deadlifts et tirages.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4o3plJe',
    imageUrl: 'https://m.media-amazon.com/images/I/61CVDZWf69L._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['sangles', 'D-ring', 'grip', 'canada'],
  },
  {
    id: 'ca-e4',
    name: 'Gymreapers Grips Haltérophilie – Néoprène',
    brand: 'Gymreapers',
    description: 'Grips de levage en caoutchouc renforcé avec wraps de poignet néoprène. Alternative aux gants.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3PAclOp',
    imageUrl: 'https://m.media-amazon.com/images/I/81XcpUJXGFL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['grips', 'poignet', 'deadlift', 'canada'],
  },
  {
    id: 'ca-e5',
    name: 'Gymreapers Coudières de Compression – 40 pouces',
    brand: 'Gymreapers',
    description: 'Bandes de coude 40" pour le bench press et le powerlifting. Soutien et stabilisation articulaire.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4wX3y9V',
    imageUrl: 'https://m.media-amazon.com/images/I/71SgEXDc2vL._SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['coudières', 'bench press', 'powerlifting', 'canada'],
  },
  {
    id: 'ca-e6',
    name: 'Slim Panda Ancrage de Porte – 5 D-Rings',
    brand: 'Slim Panda',
    description: 'Accessoire d\'ancrage de porte pour bandes de résistance. 5 points d\'attache, compatible portes jusqu\'à 2.4 m.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4wZ39Uu',
    imageUrl: 'https://m.media-amazon.com/images/I/71q97+Pb5tL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['GENERAL_FITNESS', 'MUSCLE_GAIN'],
    tags: ['ancrage', 'porte', 'bandes résistance', 'canada'],
  },
  {
    id: 'ca-e7',
    name: 'Gymreapers Sangles Cheville – Machine à Câbles',
    brand: 'Gymreapers',
    description: 'Sangles de cheville rembourrées pour kickbacks, exercices fessiers et jambes à la machine à câbles.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4dNISdb',
    imageUrl: 'https://m.media-amazon.com/images/I/71TJKCLfiqL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['sangles cheville', 'fessiers', 'câbles', 'canada'],
  },
  {
    id: 'ca-e8',
    name: 'Puroma Cadenas TSA – Pour Casier de Gym (x2)',
    brand: 'Puroma',
    description: 'Pack de 2 cadenas TSA à combinaison 4 chiffres. Idéal pour sécuriser son casier en salle de sport.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3RCzuAk',
    imageUrl: 'https://m.media-amazon.com/images/I/71igCo7CFFL._AC_SL1500_.jpg',
    commissionRateMin: 4, commissionRateMax: 7,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['cadenas', 'casier', 'gym', 'canada'],
  },
  {
    id: 'ca-e9',
    name: 'Readaeer Roue Abdominale – Ab Roller',
    brand: 'Readaeer',
    description: 'Ab wheel avec genouillère incluse. Renforce les abdominaux, le core et les bras en un mouvement.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4u08CHT',
    imageUrl: 'https://m.media-amazon.com/images/I/713McjgllML._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['WEIGHT_LOSS', 'GENERAL_FITNESS'],
    tags: ['ab wheel', 'abdos', 'core', 'canada'],
  },
  {
    id: 'ca-e10',
    name: 'Eonfit EL2 Presse à Jambes 4-en-1 – Maison',
    brand: 'Eonfit',
    description: 'Machine presse jambes inclinée 45° avec hack squat, mollets et rangement. Capacité 1300 lbs.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4uL615S',
    imageUrl: 'https://m.media-amazon.com/images/I/61-jY82VGNL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['presse jambes', 'hack squat', 'maison', 'canada'],
  },
  {
    id: 'ca-b1',
    name: 'WIZFOKO Grip Trainer Ajustable – 10-100 kg (x2)',
    brand: 'WIZFOKO',
    description: 'Pack de 2 pinces de renforcement de la prise en main. Résistance réglable de 10 à 100 kg.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4uC0HBF',
    imageUrl: 'https://m.media-amazon.com/images/I/61CGsCgv9sL._AC_SL1500_.jpg',
    commissionRateMin: 4, commissionRateMax: 7,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['grip trainer', 'avant-bras', 'force', 'canada'],
  },
  {
    id: 'ca-b2',
    name: 'Gymreapers Ceinture Lestée – Chaîne Acier',
    brand: 'Gymreapers',
    description: 'Ceinture de lest avec chaîne en acier robuste pour tractions et dips. Ajout de poids facilité.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/49wA6NZ',
    imageUrl: 'https://m.media-amazon.com/images/I/81O+1yrPX-L._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture lestée', 'tractions', 'dips', 'canada'],
  },
  {
    id: 'ca-b3',
    name: 'XIMTRA Sangles Cheville – Machine à Câbles',
    brand: 'XIMTRA',
    description: 'Sangles de cheville avec anneaux D pour fessiers, kickbacks et exercices de jambes aux câbles.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4fQbT9a',
    imageUrl: 'https://m.media-amazon.com/images/I/81PnjDoDevL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['sangles cheville', 'câbles', 'fessiers', 'canada'],
  },
  {
    id: 'ca-b6',
    name: 'DMoose Ceinture Lestée – Chaîne 36 pouces',
    brand: 'DMoose',
    description: 'Ceinture de lest avec chaîne acier 36". Néoprène rembourré, capacité 350 lbs pour dips et tractions.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4xgMAnl',
    imageUrl: 'https://m.media-amazon.com/images/I/81RgU-ALy7L._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture lestée', 'dips', 'pull-up', 'canada'],
  },

  // --- CLOTHING & ACCESSORIES ----------------------------------------------

  {
    id: 'ca-e17',
    name: 'Nike Dry Tee DRI-FIT – T-shirt Homme',
    brand: 'Nike',
    description: 'T-shirt de sport Nike Dri-FIT en coton technique. Évacuation de la transpiration, coupe décontractée.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/43zjbXE',
    imageUrl: 'https://m.media-amazon.com/images/I/71sjwwpFx2L._AC_SL1500_.jpg',
    commissionRateMin: 7, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['t-shirt', 'nike', 'dri-fit', 'canada'],
  },
  {
    id: 'ca-e19',
    name: 'Nike Everyday Cushion Chaussettes Basses – 6 paires',
    brand: 'Nike',
    description: 'Pack de 6 paires de chaussettes Nike rembourrées. Idéales pour l\'entraînement et le running.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4vnompI',
    imageUrl: 'https://m.media-amazon.com/images/I/71m3SP2cIQL._AC_SL1500_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['chaussettes', 'nike', 'running', 'canada'],
  },
  {
    id: 'ca-e20',
    name: 'Nike Dry Icon Shorts – Homme',
    brand: 'Nike',
    description: 'Short de sport Nike Dri-FIT léger et respirant. Parfait pour la salle, le cardio et le running.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4u2M0qc',
    imageUrl: 'https://m.media-amazon.com/images/I/71tq9-6xUvL._AC_SL1500_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['short', 'nike', 'dri-fit', 'canada'],
  },
  {
    id: 'ca-c1',
    name: 'PHSYNI Sac de Sport Femme – 19 pouces',
    brand: 'PHSYNI',
    description: 'Sac de gym imperméable avec compartiment chaussures séparé et poche humide. Format medium 19".',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4dSaVa6',
    imageUrl: 'https://m.media-amazon.com/images/I/71p4dUZSobL._AC_SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['sac', 'gym bag', 'femme', 'canada'],
  },
  {
    id: 'ca-c2',
    name: 'Nike Everyday Cushion Chaussettes Hautes – 6 paires',
    brand: 'Nike',
    description: 'Pack de 6 paires de chaussettes crew Nike rembourrées pour l\'entraînement quotidien.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/43BIoAD',
    imageUrl: 'https://m.media-amazon.com/images/I/81nH1kqgFYL._AC_SL1500_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['chaussettes', 'crew', 'nike', 'canada'],
  },
  {
    id: 'ca-c4',
    name: 'Nike Sport – Accessoire Fitness',
    brand: 'Nike',
    description: 'Accessoire sportif Nike. Consulter le lien pour voir les détails complets du produit.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4u3INqi',
    imageUrl: 'https://m.media-amazon.com/images/I/51Ft8KXZb6L._AC_SL1500_.jpg',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['nike', 'sport', 'canada'],
  },

  // ── LIVRES & GUIDES ──────────────────────────────────────────────────────────

  {
    id: 'ca-e11',
    name: 'Musculation du SUPER Paresseux – Jean Marchal',
    brand: 'Jean Marchal',
    description: 'Méthode de musculation au poids du corps en 7 minutes par jour. Maigrir et se muscler sans salle ni régime.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4fcsRyt',
    imageUrl: 'https://m.media-amazon.com/images/I/61I7yNMm32L._SL1436_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['WEIGHT_LOSS', 'MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['musculation', 'poids du corps', '7 minutes', 'canada'],
  },
  {
    id: 'ca-e12',
    name: 'Bigger Leaner Stronger – Michael Matthews',
    brand: 'Michael Matthews',
    description: 'La science simple pour construire le corps masculin ultime. Programme éprouvé basé sur la recherche.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4o7UlYn',
    imageUrl: 'https://m.media-amazon.com/images/I/61sU3GVMD9L._SL1430_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['bigger leaner stronger', 'science', 'musculation', 'canada'],
  },
  {
    id: 'ca-e13',
    name: 'Beginner\'s Guide to Weight Lifting – Kyle Hunt',
    brand: 'Kyle Hunt',
    description: 'Guide complet pour débutants en haltérophilie. Exercices simples et programmes pour devenir fort.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/3QeisYR',
    imageUrl: 'https://m.media-amazon.com/images/I/71ANWSDja4L._SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['débutant', 'haltérophilie', 'programme', 'canada'],
  },
  {
    id: 'ca-e14',
    name: 'Tai Chi sur Chaise pour Maigrir – Shanshani',
    brand: 'Shanshani Edition',
    description: 'Livre 3-en-1 avec 50 exercices illustrés, plan de 28 jours et plan alimentaire. Pour articulations douloureuses.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4dU1Ehw',
    imageUrl: 'https://m.media-amazon.com/images/I/61+yCHvz2ML._SL1293_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['WEIGHT_LOSS', 'FLEXIBILITY'],
    tags: ['tai chi', 'chaise', 'seniors', 'canada'],
  },
  {
    id: 'ca-e15',
    name: 'Toxic Veggies – Sally Norton',
    brand: 'Sally Norton',
    description: 'La face cachée des super-aliments : les oxalates, leurs effets sur la santé et comment les gérer.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4fcsTq5',
    imageUrl: 'https://m.media-amazon.com/images/I/71NIaD-G8vL._SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['nutrition', 'oxalates', 'super-aliments', 'canada'],
  },
  {
    id: 'ca-e16',
    name: 'Quick & Easy High Protein Low Carb Cookbook – Jeanna Miller',
    brand: 'Jeanna Miller',
    description: '100+ recettes protéinées faibles en glucides avec plan de repas de 90 jours pour perdre du poids.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/43Hw7KY',
    imageUrl: 'https://m.media-amazon.com/images/I/71HRU1R7XAL._SL1293_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['WEIGHT_LOSS', 'MUSCLE_GAIN'],
    tags: ['cuisine', 'protéines', 'low carb', 'canada'],
  },
  {
    id: 'ca-e18',
    name: 'The One 1200-Calorie Solution – Roberto Bruno',
    brand: 'Roberto Bruno',
    description: 'Plan alimentaire de 60 jours à 1200 calories avec recettes équilibrées pour une perte de poids durable.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/3RtGG1L',
    imageUrl: 'https://m.media-amazon.com/images/I/71PKBANcf4L._SL1293_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['WEIGHT_LOSS'],
    tags: ['1200 calories', 'régime', 'plan alimentaire', 'canada'],
  },
  {
    id: 'ca-c3',
    name: 'Régime Anti-Inflammatoire Complet – Oriane Bellier',
    brand: 'Oriane Bellier',
    description: '500+ recettes anti-inflammatoires avec plan alimentaire de 90 jours pour retrouver l\'équilibre.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/3Pw6Ksr',
    imageUrl: 'https://m.media-amazon.com/images/I/71ZKPCdm8dL._SL1293_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS', 'WEIGHT_LOSS'],
    tags: ['anti-inflammatoire', 'recettes', 'plan alimentaire', 'canada'],
  },
  {
    id: 'ca-c5',
    name: 'Régime Anti-Inflammatoire – Plan 90 Jours – Oriane Bellier',
    brand: 'Oriane Bellier',
    description: 'Guide complet pour apaiser l\'inflammation par l\'alimentation. 500 recettes simples et plan structuré.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4nVfepA',
    imageUrl: 'https://m.media-amazon.com/images/I/71ZKPCdm8dL._SL1293_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['anti-inflammatoire', 'nutrition', '90 jours', 'canada'],
  },
  {
    id: 'ca-c6',
    name: 'The Year One Challenge for Men – Michael Matthews',
    brand: 'Michael Matthews',
    description: 'Le défi d\'une année : devenir plus grand, plus sec et plus fort que jamais en 12 mois.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4nYtpKF',
    imageUrl: 'https://m.media-amazon.com/images/I/81CKfl-GLPL._SL1500_.jpg',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['year one challenge', 'programme', '12 mois', 'canada'],
  },
]
