import type { AffiliateProduct } from '@/types'

/**
 * Catalogue affilié Canada — 58 produits Amazon.ca entièrement indépendants du catalogue France.
 * Met à jour name, brand, description et imageUrl en visitant chaque lien Amazon pour avoir
 * les vraies métadonnées produit.
 */
export const CANADA_AFFILIATE_PRODUCTS: AffiliateProduct[] = [

  // ── SUPPLÉMENTS ─────────────────────────────────────────────────────────────

  {
    id: 'ca-s1',
    name: 'Whey Protéine – Chocolat',
    brand: 'Amazon CA',
    description: 'Protéine whey de qualité pour la prise de masse et la récupération musculaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vDrQVd',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'protéine', 'chocolat', 'canada'],
  },
  {
    id: 'ca-s2',
    name: 'Whey Protéine – Vanille',
    brand: 'Amazon CA',
    description: 'Protéine whey saveur vanille. Idéale après l\'entraînement pour la récupération.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dR5KXX',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['whey', 'protéine', 'vanille', 'canada'],
  },
  {
    id: 'ca-s3',
    name: 'Créatine Monohydrate – 500 g',
    brand: 'Amazon CA',
    description: 'Créatine monohydrate pure pour améliorer la force et la puissance musculaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4va0FRi',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['créatine', 'monohydrate', 'force', 'canada'],
  },
  {
    id: 'ca-s4',
    name: 'BCAA 2:1:1 – Fruits Tropicaux',
    brand: 'Amazon CA',
    description: 'Acides aminés ramifiés pour réduire la fatigue et accélérer la récupération.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4agpymk',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['bcaa', 'acides aminés', 'récupération', 'canada'],
  },
  {
    id: 'ca-s5',
    name: 'Pré-Entraînement – Énergie & Focus',
    brand: 'Amazon CA',
    description: 'Complexe pré-workout pour maximiser l\'énergie, la concentration et les performances.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dJhfQU',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['pre-workout', 'énergie', 'focus', 'canada'],
  },
  {
    id: 'ca-s6',
    name: 'Mass Gainer – Chocolat',
    brand: 'Amazon CA',
    description: 'Gainer haute calorie pour une prise de masse efficace. Riche en protéines et glucides.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dRiX2H',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['gainer', 'masse', 'calories', 'canada'],
  },
  {
    id: 'ca-s7',
    name: 'Oméga-3 Huile de Poisson – 120 Capsules',
    brand: 'Amazon CA',
    description: 'Oméga-3 EPA & DHA pour la santé cardiovasculaire, cérébrale et articulaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3Pu1CFe',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['oméga-3', 'EPA', 'DHA', 'canada'],
  },
  {
    id: 'ca-s8',
    name: 'Multivitamines Sport – 90 Comprimés',
    brand: 'Amazon CA',
    description: 'Multivitamines complètes pour sportifs. Vitamines A, B, C, D, E + minéraux essentiels.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vmCory',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['vitamines', 'minéraux', 'sport', 'canada'],
  },
  {
    id: 'ca-s9',
    name: 'Magnésium Glycinate – 120 Capsules',
    brand: 'Amazon CA',
    description: 'Magnésium hautement absorbable pour réduire la fatigue et améliorer le sommeil.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vdcFBB',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['magnésium', 'glycinate', 'sommeil', 'canada'],
  },
  {
    id: 'ca-s10',
    name: 'Vitamine D3 + K2 – 2000 UI',
    brand: 'Amazon CA',
    description: 'Combo D3 + K2 pour la santé osseuse, immunitaire et musculaire. Absorption optimale.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4fPZTVh',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['vitamine D3', 'K2', 'os', 'immunité', 'canada'],
  },
  {
    id: 'ca-s11',
    name: 'L-Carnitine – 1000 mg – 60 Capsules',
    brand: 'Amazon CA',
    description: 'L-Carnitine pour favoriser l\'utilisation des graisses comme source d\'énergie.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4fc3vkc',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['WEIGHT_LOSS', 'ENDURANCE'],
    tags: ['carnitine', 'brûle-graisses', 'énergie', 'canada'],
  },
  {
    id: 'ca-s12',
    name: 'Whey Isolate – Fraise',
    brand: 'Amazon CA',
    description: 'Isolat de whey ultra-filtré. Faible en glucides et lipides. Idéal en sèche.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4dRBPi5',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['whey isolate', 'fraise', 'sèche', 'canada'],
  },
  {
    id: 'ca-s13',
    name: 'EAA Acides Aminés Essentiels – Poudre',
    brand: 'Amazon CA',
    description: '9 acides aminés essentiels en poudre pour soutenir la synthèse protéique.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4flMHYd',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['EAA', 'acides aminés', 'synthèse', 'canada'],
  },
  {
    id: 'ca-s14',
    name: 'Protéine Végétale – Pois & Riz',
    brand: 'Amazon CA',
    description: 'Protéine 100% végétale, complète, sans lactose. Idéale pour les végétaliens sportifs.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4va0K7y',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['vegan', 'protéine végétale', 'pois', 'canada'],
  },
  {
    id: 'ca-s15',
    name: 'Collagène Hydrolysé – 300 g',
    brand: 'Amazon CA',
    description: 'Collagène peptides pour la santé articulaire, la peau et les tendons.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vDrXQD',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['collagène', 'articulations', 'peau', 'canada'],
  },
  {
    id: 'ca-s16',
    name: 'Glutamine – 250 g',
    brand: 'Amazon CA',
    description: 'L-Glutamine pure pour la récupération musculaire et le soutien immunitaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vdcNRB',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['glutamine', 'récupération', 'immunité', 'canada'],
  },
  {
    id: 'ca-s17',
    name: 'Brûleur de Graisse – Thermogénique',
    brand: 'Amazon CA',
    description: 'Complexe thermogénique pour stimuler le métabolisme et la perte de graisse.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vgVBuD',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['WEIGHT_LOSS'],
    tags: ['brûleur', 'thermogénique', 'métabolisme', 'canada'],
  },
  {
    id: 'ca-s18',
    name: 'Zinc + Cuivre – 50 mg – 100 Gélules',
    brand: 'Amazon CA',
    description: 'Zinc et cuivre pour le système immunitaire, la testostérone et la récupération.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3Qb5zyH',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['zinc', 'cuivre', 'immunité', 'canada'],
  },
  {
    id: 'ca-s19',
    name: 'Caséine Protéine Nuit – Chocolat',
    brand: 'Amazon CA',
    description: 'Protéine à digestion lente pour nourrir les muscles pendant le sommeil.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4wVTxK2',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['caséine', 'nuit', 'chocolat', 'canada'],
  },
  {
    id: 'ca-s20',
    name: 'Électrolytes – Hydratation Sport',
    brand: 'Amazon CA',
    description: 'Mélange d\'électrolytes pour maintenir l\'hydratation et prévenir les crampes.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4uoy8qJ',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['électrolytes', 'hydratation', 'crampes', 'canada'],
  },
  {
    id: 'ca-s21',
    name: 'Ashwagandha KSM-66 – 600 mg',
    brand: 'Amazon CA',
    description: 'Adaptogène cliniquement prouvé pour réduire le cortisol et améliorer la récupération.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4uYwFbL',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['ashwagandha', 'adaptogène', 'cortisol', 'canada'],
  },
  {
    id: 'ca-s22',
    name: 'Vitamine C – 1000 mg – 100 Comprimés',
    brand: 'Amazon CA',
    description: 'Vitamine C haute dose pour l\'immunité, l\'antioxydation et la récupération.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/43CiY5X',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['vitamine C', 'immunité', 'antioxydant', 'canada'],
  },
  {
    id: 'ca-s23',
    name: 'Pré-Workout Sans Stimulants',
    brand: 'Amazon CA',
    description: 'Pré-entraînement stim-free avec citrulline et bêta-alanine. Idéal le soir.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4vgVHCv',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE'],
    tags: ['pre-workout', 'stim-free', 'citrulline', 'canada'],
  },
  {
    id: 'ca-s24',
    name: 'Barres Protéinées – Boîte de 12',
    brand: 'Amazon CA',
    description: 'Barres riches en protéines, faibles en sucre. Collation pratique post-workout.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/4uoyb5T',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS', 'GENERAL_FITNESS'],
    tags: ['barres protéinées', 'collation', 'post-workout', 'canada'],
  },
  {
    id: 'ca-s25',
    name: 'Créatine HCl – 120 Capsules',
    brand: 'Amazon CA',
    description: 'Créatine chlorhydrate haute solubilité. Pas de phase de charge nécessaire.',
    category: 'SUPPLEMENTS',
    affiliateUrl: 'https://amzn.to/3PJlbcF',
    commissionRateMin: 8, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['créatine HCl', 'force', 'solubilité', 'canada'],
  },

  // ── ÉQUIPEMENT ───────────────────────────────────────────────────────────────

  {
    id: 'ca-e1',
    name: 'Bandes de Résistance – Set de 5 Niveaux',
    brand: 'Amazon CA',
    description: '5 bandes élastiques de résistance progressive pour la musculation et le yoga.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3PRFPHp',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['FLEXIBILITY', 'GENERAL_FITNESS', 'WEIGHT_LOSS'],
    tags: ['bandes', 'résistance', 'élastiques', 'canada'],
  },
  {
    id: 'ca-e2',
    name: 'Sangles de Levage – Nylon Rembourré',
    brand: 'Amazon CA',
    description: 'Sangles haltérophilie pour un grip supérieur lors des exercices de tirage.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/49qMsHA',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['sangles', 'levage', 'grip', 'canada'],
  },
  {
    id: 'ca-e3',
    name: 'Ceinture Lombaire – Powerlifting Néoprène',
    brand: 'Amazon CA',
    description: 'Ceinture de soutien lombaire en néoprène pour squat, deadlift et rowing.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4o3plJe',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture', 'lombaire', 'powerlifting', 'canada'],
  },
  {
    id: 'ca-e4',
    name: 'Pistolet de Massage Musculaire',
    brand: 'Amazon CA',
    description: 'Pistolet percussif pour la récupération musculaire et la réduction des courbatures.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3PAclOp',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['massage', 'percussif', 'récupération', 'canada'],
  },
  {
    id: 'ca-e5',
    name: 'Rouleau de Massage – Foam Roller 60 cm',
    brand: 'Amazon CA',
    description: 'Foam roller haute densité pour automassage, relâchement myofascial et récupération.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4wX3y9V',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['FLEXIBILITY', 'GENERAL_FITNESS'],
    tags: ['foam roller', 'massage', 'myofascial', 'canada'],
  },
  {
    id: 'ca-e6',
    name: 'Barre de Traction Porte – Sans Vissage',
    brand: 'Amazon CA',
    description: 'Barre de traction à installer sur encadrure de porte. Supporte jusqu\'à 150 kg.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4wZ39Uu',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['traction', 'barre', 'porte', 'canada'],
  },
  {
    id: 'ca-e7',
    name: 'Kettlebell – 16 kg',
    brand: 'Amazon CA',
    description: 'Kettlebell fonte pour les swings, squats et circuits de force-cardio.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4dNISdb',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'ENDURANCE', 'WEIGHT_LOSS'],
    tags: ['kettlebell', 'fonte', 'crossfit', 'canada'],
  },
  {
    id: 'ca-e8',
    name: 'Tapis de Yoga & Fitness – 6 mm',
    brand: 'Amazon CA',
    description: 'Tapis antidérapant épais 6mm pour yoga, pilates et exercices au sol.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3RCzuAk',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['FLEXIBILITY', 'GENERAL_FITNESS'],
    tags: ['tapis', 'yoga', 'antidérapant', 'canada'],
  },
  {
    id: 'ca-e9',
    name: 'Rouleau Abdominal – Ab Wheel',
    brand: 'Amazon CA',
    description: 'Roue abdominale avec genouillère pour renforcer les abdominaux et le core.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4u08CHT',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['WEIGHT_LOSS', 'GENERAL_FITNESS'],
    tags: ['abdominaux', 'ab wheel', 'core', 'canada'],
  },
  {
    id: 'ca-e10',
    name: 'Corde à Sauter – Speed Jumping Rope',
    brand: 'Amazon CA',
    description: 'Corde à sauter légère pour cardio, CrossFit et double unders. Roulements à billes.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4uL615S',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['ENDURANCE', 'WEIGHT_LOSS', 'GENERAL_FITNESS'],
    tags: ['corde', 'cardio', 'crossfit', 'canada'],
  },
  {
    id: 'ca-e11',
    name: 'Ceinture Lestée – avec Chaîne',
    brand: 'Amazon CA',
    description: 'Ceinture de lest avec chaîne pour tractions et dips. Capacité max 200 kg.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4fcsRyt',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['ceinture lestée', 'chaîne', 'dips', 'canada'],
  },
  {
    id: 'ca-e12',
    name: 'Shaker Protéiné – 700 ml',
    brand: 'Amazon CA',
    description: 'Shaker avec grille mélangeur intégrée pour protéines et autres suppléments.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4o7UlYn',
    commissionRateMin: 4, commissionRateMax: 7,
    fitnessGoals: ['GENERAL_FITNESS', 'MUSCLE_GAIN'],
    tags: ['shaker', 'bouteille', 'protéine', 'canada'],
  },
  {
    id: 'ca-e13',
    name: 'Banc de Musculation Pliant – Multiposition',
    brand: 'Amazon CA',
    description: 'Banc de musculation réglable 7 positions. Incliné, plat, décliné. Pliable.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3QeisYR',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['banc', 'musculation', 'réglable', 'canada'],
  },
  {
    id: 'ca-e14',
    name: 'Bandes Pull-Up & Assistance',
    brand: 'Amazon CA',
    description: 'Bandes élastiques épaisses pour l\'assistance aux tractions et le Powerlifting.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4dU1Ehw',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['pull-up', 'assistance', 'powerlifting', 'canada'],
  },
  {
    id: 'ca-e15',
    name: 'Ballon de Fitness – 65 cm',
    brand: 'Amazon CA',
    description: 'Ballon de gym anti-éclatement pour gainage, yoga et renforcement du core.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4fcsTq5',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['FLEXIBILITY', 'GENERAL_FITNESS'],
    tags: ['ballon', 'gym', 'core', 'canada'],
  },
  {
    id: 'ca-e16',
    name: 'Anneaux de Gymnaste – Bois',
    brand: 'Amazon CA',
    description: 'Anneaux de gym en bois pour calisthenics, dips et exercices au poids du corps.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/43Hw7KY',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['anneaux', 'calisthenics', 'bois', 'canada'],
  },
  {
    id: 'ca-e17',
    name: 'Supports Push-Up – Ergonomiques',
    brand: 'Amazon CA',
    description: 'Poignées de pompes pour réduire la pression sur les poignets et augmenter l\'amplitude.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/43zjbXE',
    commissionRateMin: 4, commissionRateMax: 7,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['push-up', 'pompes', 'poignées', 'canada'],
  },
  {
    id: 'ca-e18',
    name: 'Masseur Cervical Shiatsu',
    brand: 'Amazon CA',
    description: 'Masseur cou et épaules avec chaleur. Idéal après une séance intensive.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/3RtGG1L',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['masseur', 'shiatsu', 'cervical', 'canada'],
  },
  {
    id: 'ca-e19',
    name: 'Genouillères de Compression – Pair',
    brand: 'Amazon CA',
    description: 'Genouillères sport pour le soutien et la protection du genou lors des entraînements.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4vnompI',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['GENERAL_FITNESS', 'ENDURANCE'],
    tags: ['genouillères', 'compression', 'protection', 'canada'],
  },
  {
    id: 'ca-e20',
    name: 'Poignées de Suspension TRX-Style',
    brand: 'Amazon CA',
    description: 'Sangles de suspension polyvalentes pour l\'entraînement fonctionnel à domicile.',
    category: 'EQUIPMENT',
    affiliateUrl: 'https://amzn.to/4u2M0qc',
    commissionRateMin: 5, commissionRateMax: 9,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['suspension', 'TRX', 'fonctionnel', 'canada'],
  },

  // ── VÊTEMENTS & ACCESSOIRES ──────────────────────────────────────────────────

  {
    id: 'ca-c1',
    name: 'Gants de Musculation – Open Finger',
    brand: 'Amazon CA',
    description: 'Gants de sport open-finger pour CrossFit, haltérophilie et calisthenics.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4dSaVa6',
    commissionRateMin: 7, commissionRateMax: 12,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['gants', 'crossfit', 'grip', 'canada'],
  },
  {
    id: 'ca-c2',
    name: 'Coudières de Compression',
    brand: 'Amazon CA',
    description: 'Coudières sport pour le soutien et la stabilisation du coude lors de la musculation.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/43BIoAD',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['coudières', 'compression', 'coude', 'canada'],
  },
  {
    id: 'ca-c3',
    name: 'Wraps de Poignet – Powerlifting',
    brand: 'Amazon CA',
    description: 'Bandages de poignet pour protéger et stabiliser lors des soulevés lourds.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/3Pw6Ksr',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['wraps', 'poignet', 'powerlifting', 'canada'],
  },
  {
    id: 'ca-c4',
    name: 'Chaussettes de Compression – Running',
    brand: 'Amazon CA',
    description: 'Chaussettes de compression pour améliorer la circulation et réduire la fatigue.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4u3INqi',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['ENDURANCE', 'GENERAL_FITNESS'],
    tags: ['chaussettes', 'compression', 'running', 'canada'],
  },
  {
    id: 'ca-c5',
    name: 'Sac de Sport Fitness – 40 L',
    brand: 'Amazon CA',
    description: 'Sac de sport spacieux avec compartiment chaussures séparé et porte-bouteille.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4nVfepA',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS'],
    tags: ['sac', 'sport', 'gym bag', 'canada'],
  },
  {
    id: 'ca-c6',
    name: 'Ceinture de Sudation Néoprène',
    brand: 'Amazon CA',
    description: 'Ceinture abdominale néoprène pour stimuler la transpiration et soutenir la sangle.',
    category: 'CLOTHING',
    affiliateUrl: 'https://amzn.to/4nYtpKF',
    commissionRateMin: 6, commissionRateMax: 10,
    fitnessGoals: ['WEIGHT_LOSS'],
    tags: ['sudation', 'néoprène', 'abdos', 'canada'],
  },

  // ── LIVRES & GUIDES ──────────────────────────────────────────────────────────

  {
    id: 'ca-b1',
    name: 'Strength Training Anatomy – Frédéric Delavier',
    brand: 'Human Kinetics',
    description: 'La référence mondiale de l\'anatomie de la musculation. Illustré, en anglais.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4uC0HBF',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN'],
    tags: ['anatomie', 'musculation', 'référence', 'canada'],
  },
  {
    id: 'ca-b2',
    name: 'Guide Nutrition Sportive – Macros & Performance',
    brand: 'Amazon CA',
    description: 'Tout sur les macronutriments, le timing des repas et l\'alimentation du sportif.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/49wA6NZ',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS', 'GENERAL_FITNESS'],
    tags: ['nutrition', 'macros', 'performance', 'canada'],
  },
  {
    id: 'ca-b3',
    name: 'Programme 12 Semaines – Perte de Poids',
    brand: 'Amazon CA',
    description: 'Plan d\'entraînement et de nutrition sur 12 semaines pour perdre du poids durablement.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4fQbT9a',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['WEIGHT_LOSS'],
    tags: ['programme', '12 semaines', 'perte de poids', 'canada'],
  },
  {
    id: 'ca-b4',
    name: 'Carnet d\'Entraînement – Suivi des Progrès',
    brand: 'Amazon CA',
    description: 'Carnet de suivi d\'entraînement pour noter ses séances et suivre ses progrès.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/43DyEG8',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['GENERAL_FITNESS', 'MUSCLE_GAIN'],
    tags: ['carnet', 'suivi', 'progrès', 'canada'],
  },
  {
    id: 'ca-b5',
    name: 'Guide Complet Calisthenics',
    brand: 'Amazon CA',
    description: 'Maîtrisez le poids du corps du niveau débutant à expert. Progressions détaillées.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4wXXSfL',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'GENERAL_FITNESS'],
    tags: ['calisthenics', 'poids du corps', 'progressions', 'canada'],
  },
  {
    id: 'ca-b6',
    name: 'Recettes Protéinées – 100 Idées Repas',
    brand: 'Amazon CA',
    description: '100 recettes riches en protéines pour les sportifs. Simples, rapides et équilibrées.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4xgMAnl',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['recettes', 'protéines', 'sport', 'canada'],
  },
  {
    id: 'ca-b7',
    name: 'Bigger Leaner Stronger – Michael Matthews',
    brand: 'Oculus Publishers',
    description: 'La méthode scientifique simple et efficace pour devenir plus grand, plus sec et plus fort.',
    category: 'BOOKS',
    affiliateUrl: 'https://amzn.to/4ecTKBh',
    commissionRateMin: 5, commissionRateMax: 8,
    fitnessGoals: ['MUSCLE_GAIN', 'WEIGHT_LOSS'],
    tags: ['bigger leaner stronger', 'musculation', 'science', 'canada'],
  },
]
